@PORT = 3307
@HOST = http://localhost:{{PORT}}


GET {{HOST}}/api/autores

### 
GET {{HOST}}/api/autores/1

### 
POST {{HOST}}/api/autores
Content-Type: application/json

{
  "nombre": "Faustino Merlo", 
  "email" : "Faustino@example.com",
  "imagen" : "imagen9.jpg"
}

### 
PUT {{HOST}}/api/autores/6
Content-Type: application/json

{
  "nombre": "Sofia Terraga",
  "email" : "sofiafernandez@example.com",
  "imagen" : "imagen6.jpg"
}

### 
DELETE {{HOST}}/api/autores/17