@PORT = 3307
@HOST = http://localhost:{{PORT}}

### 
GET {{HOST}}/api/posts

### 
GET {{HOST}}/api/posts/7

### 
GET {{HOST}}/api/posts/autor/2

### 
POST {{HOST}}/api/posts
Content-Type: application/json

{
  "titulo": "Formula 1",
  "descripcion" : "Estamos esperando que empiece la temporada de F1, y que Fernando Alonso vuelva a ganar un campeonato",
  "categoria" : "Deporte",
  "autor_id" : "17"
  }

### 
PUT {{HOST}}/api/posts
Content-Type: application/json

{
    "titulo": "Los secretos de la cocina italiana 2", 
    "descripcion": "Un viaje culinario a través de la cocina italiana. Desde la pizza napolitana hasta la pasta fresca, descubre los secretos de la auténtica cocina italiana.",
    "categoria": "Cocina",
    "autor_id": "2"
  }

### 
DELETE {{HOST}}/api/posts/13